=== marianabarreto891/Health-Time-Integracao-de-Tempos-de-Espera-Hospitalares-/Consultations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    
    
    <xs:simpleType name="TargetPopulationType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Adulto"/>
            <xs:enumeration value="Criança"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="priorityType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Normal"/>
            <xs:enumeration value="Prioritário"/>
            <xs:enumeration value="Muito Prioritário"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="NonNegativeDecimal">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
 
    <xs:element name="ConsultationsRegister">
        <xs:complexType>
            <xs:sequence>

                
                <xs:element name="Header">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="InstitutionId" type="xs:int"/>
                            <xs:element name="HospitalName" type="xs:string"/>
                            <xs:element name="Period">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Month">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:int">
                                                    <xs:minInclusive value="1"/>
                                                    <xs:maxInclusive value="12"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Year" type="xs:int"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                

                <xs:element name="Data">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Consultation" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        
                                        <xs:element name="Speciality" type="xs:string"/>
                                        <xs:element name="servicekey" type="xs:nonNegativeInteger"/>
                                        <xs:element name="TargetPopulation" type="TargetPopulationType"/>
                                        
                                        
                                        <xs:element name="WaitingListCounts">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="General" type="xs:nonNegativeInteger"/>
                                                    <xs:element name="NonOncological" type="xs:nonNegativeInteger"/>
                                                    <xs:element name="Oncological" type="xs:nonNegativeInteger"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                       
                                        
                                        <xs:element name="AverageResponseTimes">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Normal" type="NonNegativeDecimal"/>
                                                    <xs:element name="Priority" type="NonNegativeDecimal"/>
                                                    <xs:element name="VeryPriority" type="NonNegativeDecimal"/>
                                                </xs:sequence>
                                                <xs:attribute name="units" type="xs:string" use="optional"/>
                                            </xs:complexType>
                                        </xs:element>

                                    <xs:element name="priority" type="priorityType"/>
                                        
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== marianabarreto891/Health-Time-Integracao-de-Tempos-de-Espera-Hospitalares-/consultasXMLExemplo.xml
<?xml version="1.0" encoding="UTF-8"?>
<ConsultationsRegister
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Consultations.xsd">
    
    <Header>
        <InstitutionId>1</InstitutionId>
        <HospitalName>Teste</HospitalName>
        <Period>
            <Month>1</Month>
            <Year>2025</Year>
        </Period>
    </Header>
    
    <Data>
        <Consultation> 
            <Speciality>Cirurgia - CR Cancro Hepatobilio/Pancreático</Speciality>
            <servicekey>37</servicekey>
            <TargetPopulation>Adulto</TargetPopulation>
            
            <WaitingListCounts>
                <General>100</General>
                <NonOncological>90</NonOncological>
                <Oncological>10</Oncological>
            </WaitingListCounts>
            
            <AverageResponseTimes>
                <Normal>10</Normal>
                <Priority>5</Priority>
                <VeryPriority>1</VeryPriority>
            </AverageResponseTimes>
            <priority>Normal</priority>
        </Consultation>
    </Data>
    
</ConsultationsRegister>
