=== marianabarreto891/Health-Time-Integracao-de-Tempos-de-Espera-Hospitalares-/Sugeri.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    

    
    <xs:simpleType name="NonNegativeDecimal">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="priorityType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="0 - Sem prioridade"/>
            <xs:enumeration value="1 - Doença não oncológica"/>
            <xs:enumeration value="2 - Doença oncológica"/>
        </xs:restriction>
    </xs:simpleType>
    

    
    <xs:complexType name="WaitingListCountsType">
        <xs:sequence>
            <xs:element name="General" type="xs:nonNegativeInteger"/>
            <xs:element name="NonOncological" type="xs:nonNegativeInteger"/>
            <xs:element name="Oncological" type="xs:nonNegativeInteger"/>
        </xs:sequence>
    </xs:complexType>
    

    
    <xs:element name="SurgeryReport">
        <xs:complexType>
            <xs:sequence>
                
  
                
                <xs:element name="Header">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="InstitutionId" type="xs:nonNegativeInteger"/>
                            <xs:element name="ReferencePeriod" type="xs:gYearMonth"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
               
                
                <xs:element name="SurgicalData">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="SurgeryEntry" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Specialty" type="xs:string"/>
                                        <xs:element name="serviceId" type="xs:nonNegativeInteger"/>
                                        <xs:element name="priority" type ="priorityType"/>
                                        <xs:element name="WaitingListCounts" type="WaitingListCountsType"/>
                                        <xs:element name="AverageWaitTimeDays" type="NonNegativeDecimal"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== marianabarreto891/Health-Time-Integracao-de-Tempos-de-Espera-Hospitalares-/cirugiaXMLExemplo.xml
<?xml version="1.0" encoding="UTF-8"?>
<SurgeryReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Sugeri.xsd">
    <Header>
        <InstitutionId>151</InstitutionId>
        <ReferencePeriod>2025-11</ReferencePeriod>
    </Header>
    <SurgicalData>
        
        <SurgeryEntry>
            <Specialty>Cirurgia Plástica e Reconstrutiva</Specialty>
            <serviceId>95</serviceId>
            <priority>1 - Doença não oncológica</priority>
            <WaitingListCounts>
                <General>300</General>
                <NonOncological>298</NonOncological>
                <Oncological>2</Oncological>
            </WaitingListCounts>
            <AverageWaitTimeDays>120.5</AverageWaitTimeDays>
        </SurgeryEntry>
        
    </SurgicalData>
</SurgeryReport>
